name: Issue Labeler

on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install Dependencies
        run: |
          npm install
          npm install compromise lodash
      - name: Run labeler
        run: node .github/scripts/labeler.js
        env:
          REPO_TOKEN: ${{ secrets.PAT_ISSUE_LABELER }} # use the name of your secret here
